### ISSUE TITLE
`mean` of fixed-point numbers is a `Float64`

### ISSUE THREAD

**Issue by jariji** [JuliaMath/FixedPointNumbers.jl#306]
```jl
using Statistics, FixedPointNumbers

julia> typeof(mean([(N0f8(.5)), (N0f8(.5))]))
Float64
```

Is this the intended behavior? I expected it would round to the nearest fixed-point number.

**Comment by kimikage** [comment]
At least that is the behavior @timholy intended.
cf. https://github.com/JuliaMath/FixedPointNumbers.jl/pull/183, https://github.com/JuliaStats/Statistics.jl/issues/165#issue-2229522613

**Comment by kimikage** [comment]
Note that it is not a good idea to use `Float32` for the `N0f8` value accumulations. `N24f8` is superior in both speed and accuracy.

**Comment by kimikage** [comment]
As implied above, `UInt8` is a counterexample to your expectation.
```julia
julia> 0x80 + 0x80 |> typeof
UInt8

julia> reduce(+, [0x80, 0x80]) |> typeof
UInt8

julia> sum([0x80, 0x80]) |> typeof
UInt64

julia> 0xff/2 |> typeof
Float64
```
Of course, since fixed-point numbers are different from both integers and floating-point numbers, this package can and shall design its own rules. And, there is already a design.
In other words, I think it is you who must provide the "objective" rationale.

**Comment by kimikage** [comment]
I am planning to change the design once Statistics.jl provides a richer public API.
However, I think the return types will remain as they are.
